@echo off
echo Starting URANIII API Server on port 8000...
echo Opening Admin Dashboard...
start "" "http://localhost:8000/admin.html"
echo Opening Showcase...
start "" "http://localhost:8000/index.html"
python server.py
pause
